package com.marketPlace.hibernate;
// Generated 04-mar-2014 16:40:25 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Adjuntos generated by hbm2java
 */
public class Adjuntos  implements java.io.Serializable {


     private Integer id;
     private String descripcion;
     private Set<Archivosadjuntos> archivosadjuntoses = new HashSet<Archivosadjuntos>(0);

    public Adjuntos() {
    }

	
    public Adjuntos(String descripcion) {
        this.descripcion = descripcion;
    }
    public Adjuntos(String descripcion, Set<Archivosadjuntos> archivosadjuntoses) {
       this.descripcion = descripcion;
       this.archivosadjuntoses = archivosadjuntoses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Archivosadjuntos> getArchivosadjuntoses() {
        return this.archivosadjuntoses;
    }
    
    public void setArchivosadjuntoses(Set<Archivosadjuntos> archivosadjuntoses) {
        this.archivosadjuntoses = archivosadjuntoses;
    }




}


