package com.marketPlace.hibernate;
// Generated 04-mar-2014 16:40:25 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Categorias generated by hbm2java
 */
public class Categorias  implements java.io.Serializable {


     private Integer id;
     private String descripcion;
     private Set<Servicios> servicioses = new HashSet<Servicios>(0);

    public Categorias() {
    }

	
    public Categorias(String descripcion) {
        this.descripcion = descripcion;
    }
    public Categorias(String descripcion, Set<Servicios> servicioses) {
       this.descripcion = descripcion;
       this.servicioses = servicioses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Servicios> getServicioses() {
        return this.servicioses;
    }
    
    public void setServicioses(Set<Servicios> servicioses) {
        this.servicioses = servicioses;
    }




}


