package com.marketPlace.hibernate;
// Generated 04-mar-2014 16:40:25 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Ofertas generated by hbm2java
 */
public class Ofertas  implements java.io.Serializable {


     private Integer id;
     private Paquetes paquetes;
     private String descripcion;
     private Date fechaInicial;
     private Date fechaFinal;
     private int valor;
     private Set<Transacciones> transaccioneses = new HashSet<Transacciones>(0);

    public Ofertas() {
    }

	
    public Ofertas(Paquetes paquetes, String descripcion, Date fechaInicial, Date fechaFinal, int valor) {
        this.paquetes = paquetes;
        this.descripcion = descripcion;
        this.fechaInicial = fechaInicial;
        this.fechaFinal = fechaFinal;
        this.valor = valor;
    }
    public Ofertas(Paquetes paquetes, String descripcion, Date fechaInicial, Date fechaFinal, int valor, Set<Transacciones> transaccioneses) {
       this.paquetes = paquetes;
       this.descripcion = descripcion;
       this.fechaInicial = fechaInicial;
       this.fechaFinal = fechaFinal;
       this.valor = valor;
       this.transaccioneses = transaccioneses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Paquetes getPaquetes() {
        return this.paquetes;
    }
    
    public void setPaquetes(Paquetes paquetes) {
        this.paquetes = paquetes;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFechaInicial() {
        return this.fechaInicial;
    }
    
    public void setFechaInicial(Date fechaInicial) {
        this.fechaInicial = fechaInicial;
    }
    public Date getFechaFinal() {
        return this.fechaFinal;
    }
    
    public void setFechaFinal(Date fechaFinal) {
        this.fechaFinal = fechaFinal;
    }
    public int getValor() {
        return this.valor;
    }
    
    public void setValor(int valor) {
        this.valor = valor;
    }
    public Set<Transacciones> getTransaccioneses() {
        return this.transaccioneses;
    }
    
    public void setTransaccioneses(Set<Transacciones> transaccioneses) {
        this.transaccioneses = transaccioneses;
    }




}


