package com.marketPlace.hibernate;
// Generated 04-mar-2014 16:40:25 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Paquetes generated by hbm2java
 */
public class Paquetes  implements java.io.Serializable {


     private Integer id;
     private Usuarios usuarios;
     private String descripcion;
     private double valor;
     private boolean estado;
     private Set<Paquetesdeservicios> paquetesdeservicioses = new HashSet<Paquetesdeservicios>(0);
     private Set<Ofertas> ofertases = new HashSet<Ofertas>(0);
     private Set<Transacciones> transaccioneses = new HashSet<Transacciones>(0);

    public Paquetes() {
    }

	
    public Paquetes(Usuarios usuarios, String descripcion, double valor, boolean estado) {
        this.usuarios = usuarios;
        this.descripcion = descripcion;
        this.valor = valor;
        this.estado = estado;
    }
    public Paquetes(Usuarios usuarios, String descripcion, double valor, boolean estado, Set<Paquetesdeservicios> paquetesdeservicioses, Set<Ofertas> ofertases, Set<Transacciones> transaccioneses) {
       this.usuarios = usuarios;
       this.descripcion = descripcion;
       this.valor = valor;
       this.estado = estado;
       this.paquetesdeservicioses = paquetesdeservicioses;
       this.ofertases = ofertases;
       this.transaccioneses = transaccioneses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public double getValor() {
        return this.valor;
    }
    
    public void setValor(double valor) {
        this.valor = valor;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public Set<Paquetesdeservicios> getPaquetesdeservicioses() {
        return this.paquetesdeservicioses;
    }
    
    public void setPaquetesdeservicioses(Set<Paquetesdeservicios> paquetesdeservicioses) {
        this.paquetesdeservicioses = paquetesdeservicioses;
    }
    public Set<Ofertas> getOfertases() {
        return this.ofertases;
    }
    
    public void setOfertases(Set<Ofertas> ofertases) {
        this.ofertases = ofertases;
    }
    public Set<Transacciones> getTransaccioneses() {
        return this.transaccioneses;
    }
    
    public void setTransaccioneses(Set<Transacciones> transaccioneses) {
        this.transaccioneses = transaccioneses;
    }




}


