package com.marketPlace.hibernate;
// Generated 04-mar-2014 16:40:25 by Hibernate Tools 3.6.0



/**
 * Permisos generated by hbm2java
 */
public class Permisos  implements java.io.Serializable {


     private Integer id;
     private Perfiles perfiles;
     private String opciones;

    public Permisos() {
    }

    public Permisos(Perfiles perfiles, String opciones) {
       this.perfiles = perfiles;
       this.opciones = opciones;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Perfiles getPerfiles() {
        return this.perfiles;
    }
    
    public void setPerfiles(Perfiles perfiles) {
        this.perfiles = perfiles;
    }
    public String getOpciones() {
        return this.opciones;
    }
    
    public void setOpciones(String opciones) {
        this.opciones = opciones;
    }




}


