package com.marketPlace.hibernate;
// Generated 04-mar-2014 16:40:25 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Transacciones generated by hbm2java
 */
public class Transacciones  implements java.io.Serializable {


     private Integer id;
     private Paquetes paquetes;
     private Usuarios usuarios;
     private Ofertas ofertas;
     private Servicios servicios;
     private Date fechaTransaccion;

    public Transacciones() {
    }

	
    public Transacciones(Usuarios usuarios, Date fechaTransaccion) {
        this.usuarios = usuarios;
        this.fechaTransaccion = fechaTransaccion;
    }
    public Transacciones(Paquetes paquetes, Usuarios usuarios, Ofertas ofertas, Servicios servicios, Date fechaTransaccion) {
       this.paquetes = paquetes;
       this.usuarios = usuarios;
       this.ofertas = ofertas;
       this.servicios = servicios;
       this.fechaTransaccion = fechaTransaccion;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Paquetes getPaquetes() {
        return this.paquetes;
    }
    
    public void setPaquetes(Paquetes paquetes) {
        this.paquetes = paquetes;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public Ofertas getOfertas() {
        return this.ofertas;
    }
    
    public void setOfertas(Ofertas ofertas) {
        this.ofertas = ofertas;
    }
    public Servicios getServicios() {
        return this.servicios;
    }
    
    public void setServicios(Servicios servicios) {
        this.servicios = servicios;
    }
    public Date getFechaTransaccion() {
        return this.fechaTransaccion;
    }
    
    public void setFechaTransaccion(Date fechaTransaccion) {
        this.fechaTransaccion = fechaTransaccion;
    }




}


