package com.marketPlace.hibernate;
// Generated 04-mar-2014 16:40:25 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Archivos generated by hbm2java
 */
public class Archivos  implements java.io.Serializable {


     private Integer id;
     private String tipo;
     private String ruta;
     private Set<Archivosadjuntos> archivosadjuntoses = new HashSet<Archivosadjuntos>(0);

    public Archivos() {
    }

	
    public Archivos(String tipo, String ruta) {
        this.tipo = tipo;
        this.ruta = ruta;
    }
    public Archivos(String tipo, String ruta, Set<Archivosadjuntos> archivosadjuntoses) {
       this.tipo = tipo;
       this.ruta = ruta;
       this.archivosadjuntoses = archivosadjuntoses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getRuta() {
        return this.ruta;
    }
    
    public void setRuta(String ruta) {
        this.ruta = ruta;
    }
    public Set<Archivosadjuntos> getArchivosadjuntoses() {
        return this.archivosadjuntoses;
    }
    
    public void setArchivosadjuntoses(Set<Archivosadjuntos> archivosadjuntoses) {
        this.archivosadjuntoses = archivosadjuntoses;
    }




}


