package com.marketPlace.hibernate;
// Generated 04-mar-2014 16:40:25 by Hibernate Tools 3.6.0



/**
 * Paquetesdeservicios generated by hbm2java
 */
public class Paquetesdeservicios  implements java.io.Serializable {


     private Integer id;
     private Paquetes paquetes;
     private Servicios servicios;
     private boolean estado;

    public Paquetesdeservicios() {
    }

    public Paquetesdeservicios(Paquetes paquetes, Servicios servicios, boolean estado) {
       this.paquetes = paquetes;
       this.servicios = servicios;
       this.estado = estado;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Paquetes getPaquetes() {
        return this.paquetes;
    }
    
    public void setPaquetes(Paquetes paquetes) {
        this.paquetes = paquetes;
    }
    public Servicios getServicios() {
        return this.servicios;
    }
    
    public void setServicios(Servicios servicios) {
        this.servicios = servicios;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }




}


