package com.marketPlace.hibernate;
// Generated 04-mar-2014 16:40:25 by Hibernate Tools 3.6.0

import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;

/**
 * Perfiles generated by hbm2java
 */
public class Perfiles implements java.io.Serializable {

  private int id;
  private String descripcion;
  private boolean estado;
  private ArrayList<Usuarios> usuarioses = new ArrayList<Usuarios>(0);
  private ArrayList<Permisos> permisoses = new ArrayList<Permisos>(0);

  public Perfiles() {
  }

  public Perfiles(int id, String descripcion, boolean estado) {
    this.id = id;
    this.descripcion = descripcion;
    this.estado = estado;
  }

  public Perfiles(int id, String descripcion, boolean estado, ArrayList<Usuarios> usuarioses, ArrayList<Permisos> permisoses) {
    this.id = id;
    this.descripcion = descripcion;
    this.estado = estado;
    this.usuarioses = usuarioses;
    this.permisoses = permisoses;
  }

  public int getId() {
    return this.id;
  }

  public void setId(int id) {
    this.id = id;
  }

  public String getDescripcion() {
    return this.descripcion;
  }

  public void setDescripcion(String descripcion) {
    this.descripcion = descripcion;
  }

  public boolean isEstado() {
    return this.estado;
  }

  public void setEstado(boolean estado) {
    this.estado = estado;
  }

  public ArrayList<Usuarios> getUsuarioses() {
    return this.usuarioses;
  }

  public void setUsuarioses(ArrayList<Usuarios> usuarioses) {
    this.usuarioses = usuarioses;
  }

  public ArrayList<Permisos> getPermisoses() {
    return this.permisoses;
  }

  public void setPermisoses(ArrayList<Permisos> permisoses) {
    this.permisoses = permisoses;
  }

}
