package com.marketPlace.hibernate;
// Generated 04-mar-2014 16:40:25 by Hibernate Tools 3.6.0



/**
 * Preguntas generated by hbm2java
 */
public class Preguntas  implements java.io.Serializable {


     private Integer id;
     private Usuarios usuariosByIdProveedor;
     private Usuarios usuariosByIdUsuario;
     private String pregunta;
     private String respuesta;
     private boolean estado;

    public Preguntas() {
    }

    public Preguntas(Usuarios usuariosByIdProveedor, Usuarios usuariosByIdUsuario, String pregunta, String respuesta, boolean estado) {
       this.usuariosByIdProveedor = usuariosByIdProveedor;
       this.usuariosByIdUsuario = usuariosByIdUsuario;
       this.pregunta = pregunta;
       this.respuesta = respuesta;
       this.estado = estado;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Usuarios getUsuariosByIdProveedor() {
        return this.usuariosByIdProveedor;
    }
    
    public void setUsuariosByIdProveedor(Usuarios usuariosByIdProveedor) {
        this.usuariosByIdProveedor = usuariosByIdProveedor;
    }
    public Usuarios getUsuariosByIdUsuario() {
        return this.usuariosByIdUsuario;
    }
    
    public void setUsuariosByIdUsuario(Usuarios usuariosByIdUsuario) {
        this.usuariosByIdUsuario = usuariosByIdUsuario;
    }
    public String getPregunta() {
        return this.pregunta;
    }
    
    public void setPregunta(String pregunta) {
        this.pregunta = pregunta;
    }
    public String getRespuesta() {
        return this.respuesta;
    }
    
    public void setRespuesta(String respuesta) {
        this.respuesta = respuesta;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }




}


