package com.marketPlace.hibernate;
// Generated 04-mar-2014 16:40:25 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private int id;
     private Perfiles perfiles;
     private String primerNombre;
     private String segundoNombre;
     private String primerApellido;
     private String segundoApellido;
     private String nickname;
     private String contrasena;
     private String correo;
     private boolean estado;
     private Set<Transacciones> transaccioneses = new HashSet<Transacciones>(0);
     private Set<Preguntas> preguntasesForIdProveedor = new HashSet<Preguntas>(0);
     private Set<Preguntas> preguntasesForIdUsuario = new HashSet<Preguntas>(0);
     private Set<Paquetes> paqueteses = new HashSet<Paquetes>(0);

    public Usuarios() {
    }

	
    public Usuarios(int id, Perfiles perfiles, String primerNombre, String primerApellido, String nickname, String contrasena, String correo, boolean estado) {
        this.id = id;
        this.perfiles = perfiles;
        this.primerNombre = primerNombre;
        this.primerApellido = primerApellido;
        this.nickname = nickname;
        this.contrasena = contrasena;
        this.correo = correo;
        this.estado = estado;
    }
    public Usuarios(int id, Perfiles perfiles, String primerNombre, String segundoNombre, String primerApellido, String segundoApellido, String nickname, String contrasena, String correo, boolean estado, Set<Transacciones> transaccioneses, Set<Preguntas> preguntasesForIdProveedor, Set<Preguntas> preguntasesForIdUsuario, Set<Paquetes> paqueteses) {
       this.id = id;
       this.perfiles = perfiles;
       this.primerNombre = primerNombre;
       this.segundoNombre = segundoNombre;
       this.primerApellido = primerApellido;
       this.segundoApellido = segundoApellido;
       this.nickname = nickname;
       this.contrasena = contrasena;
       this.correo = correo;
       this.estado = estado;
       this.transaccioneses = transaccioneses;
       this.preguntasesForIdProveedor = preguntasesForIdProveedor;
       this.preguntasesForIdUsuario = preguntasesForIdUsuario;
       this.paqueteses = paqueteses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Perfiles getPerfiles() {
        return this.perfiles;
    }
    
    public void setPerfiles(Perfiles perfiles) {
        this.perfiles = perfiles;
    }
    public String getPrimerNombre() {
        return this.primerNombre;
    }
    
    public void setPrimerNombre(String primerNombre) {
        this.primerNombre = primerNombre;
    }
    public String getSegundoNombre() {
        return this.segundoNombre;
    }
    
    public void setSegundoNombre(String segundoNombre) {
        this.segundoNombre = segundoNombre;
    }
    public String getPrimerApellido() {
        return this.primerApellido;
    }
    
    public void setPrimerApellido(String primerApellido) {
        this.primerApellido = primerApellido;
    }
    public String getSegundoApellido() {
        return this.segundoApellido;
    }
    
    public void setSegundoApellido(String segundoApellido) {
        this.segundoApellido = segundoApellido;
    }
    public String getNickname() {
        return this.nickname;
    }
    
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public Set<Transacciones> getTransaccioneses() {
        return this.transaccioneses;
    }
    
    public void setTransaccioneses(Set<Transacciones> transaccioneses) {
        this.transaccioneses = transaccioneses;
    }
    public Set<Preguntas> getPreguntasesForIdProveedor() {
        return this.preguntasesForIdProveedor;
    }
    
    public void setPreguntasesForIdProveedor(Set<Preguntas> preguntasesForIdProveedor) {
        this.preguntasesForIdProveedor = preguntasesForIdProveedor;
    }
    public Set<Preguntas> getPreguntasesForIdUsuario() {
        return this.preguntasesForIdUsuario;
    }
    
    public void setPreguntasesForIdUsuario(Set<Preguntas> preguntasesForIdUsuario) {
        this.preguntasesForIdUsuario = preguntasesForIdUsuario;
    }
    public Set<Paquetes> getPaqueteses() {
        return this.paqueteses;
    }
    
    public void setPaqueteses(Set<Paquetes> paqueteses) {
        this.paqueteses = paqueteses;
    }




}


